version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - "POSTGRES_PASSWORD=123"
    ports:
      - "5555:5432"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: './server'
    volumes:
      - "/app/node_modules"
      - "./server:/app"
    environment:
      - "PORT=5000"
      - "DB_NAME=yiabd2"
      - "DB_USER=postgres"
      - "DB_PASSWORD=123"
      - "DB_HOST=postgres"
      - "DB_PORT=5432"
    ports:
      - "5000:5000"
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - "/app/node_modules"
      - "./client:/app"
    ports:
      - "8080:3000"
