export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const SHOP_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const PRODUCT_ROUTE = '/product'
export const REGISTRATION_ROUTE = '/registration'